#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("XLabs.Sample.Droid.Resource", IsApplication=true)]

namespace XLabs.Sample.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::XLabs.Sample.Droid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::XLabs.Sample.Droid.Resource.String.Hello;
			global::XLabs.Forms.Resource.Color.calendar_active_month_bg = global::XLabs.Sample.Droid.Resource.Color.calendar_active_month_bg;
			global::XLabs.Forms.Resource.Color.calendar_bg = global::XLabs.Sample.Droid.Resource.Color.calendar_bg;
			global::XLabs.Forms.Resource.Color.calendar_divider = global::XLabs.Sample.Droid.Resource.Color.calendar_divider;
			global::XLabs.Forms.Resource.Color.calendar_highlighted_day_bg = global::XLabs.Sample.Droid.Resource.Color.calendar_highlighted_day_bg;
			global::XLabs.Forms.Resource.Color.calendar_inactive_month_bg = global::XLabs.Sample.Droid.Resource.Color.calendar_inactive_month_bg;
			global::XLabs.Forms.Resource.Color.calendar_selected_day_bg = global::XLabs.Sample.Droid.Resource.Color.calendar_selected_day_bg;
			global::XLabs.Forms.Resource.Color.calendar_selected_range_bg = global::XLabs.Sample.Droid.Resource.Color.calendar_selected_range_bg;
			global::XLabs.Forms.Resource.Color.calendar_text_active = global::XLabs.Sample.Droid.Resource.Color.calendar_text_active;
			global::XLabs.Forms.Resource.Color.calendar_text_inactive = global::XLabs.Sample.Droid.Resource.Color.calendar_text_inactive;
			global::XLabs.Forms.Resource.Color.calendar_text_selected = global::XLabs.Sample.Droid.Resource.Color.calendar_text_selected;
			global::XLabs.Forms.Resource.Color.calendar_text_selector = global::XLabs.Sample.Droid.Resource.Color.calendar_text_selector;
			global::XLabs.Forms.Resource.Color.calendar_text_unselectable = global::XLabs.Sample.Droid.Resource.Color.calendar_text_unselectable;
			global::XLabs.Forms.Resource.Dimension.calendar_day_headers_paddingbottom = global::XLabs.Sample.Droid.Resource.Dimension.calendar_day_headers_paddingbottom;
			global::XLabs.Forms.Resource.Dimension.calendar_month_title_bottommargin = global::XLabs.Sample.Droid.Resource.Dimension.calendar_month_title_bottommargin;
			global::XLabs.Forms.Resource.Dimension.calendar_month_topmargin = global::XLabs.Sample.Droid.Resource.Dimension.calendar_month_topmargin;
			global::XLabs.Forms.Resource.Dimension.calendar_text_medium = global::XLabs.Sample.Droid.Resource.Dimension.calendar_text_medium;
			global::XLabs.Forms.Resource.Dimension.calendar_text_small = global::XLabs.Sample.Droid.Resource.Dimension.calendar_text_small;
			global::XLabs.Forms.Resource.Drawable.ad16 = global::XLabs.Sample.Droid.Resource.Drawable.ad16;
			global::XLabs.Forms.Resource.Drawable.calendar_bg_selector = global::XLabs.Sample.Droid.Resource.Drawable.calendar_bg_selector;
			global::XLabs.Forms.Resource.Id.calendar_grid = global::XLabs.Sample.Droid.Resource.Id.calendar_grid;
			global::XLabs.Forms.Resource.Id.calendar_view = global::XLabs.Sample.Droid.Resource.Id.calendar_view;
			global::XLabs.Forms.Resource.Id.left_arrow = global::XLabs.Sample.Droid.Resource.Id.left_arrow;
			global::XLabs.Forms.Resource.Id.right_arrow = global::XLabs.Sample.Droid.Resource.Id.right_arrow;
			global::XLabs.Forms.Resource.Id.title = global::XLabs.Sample.Droid.Resource.Id.title;
			global::XLabs.Forms.Resource.Layout.calendar_pager_layout = global::XLabs.Sample.Droid.Resource.Layout.calendar_pager_layout;
			global::XLabs.Forms.Resource.Layout.calendar_picker = global::XLabs.Sample.Droid.Resource.Layout.calendar_picker;
			global::XLabs.Forms.Resource.Layout.dialog = global::XLabs.Sample.Droid.Resource.Layout.dialog;
			global::XLabs.Forms.Resource.Layout.month = global::XLabs.Sample.Droid.Resource.Layout.month;
			global::XLabs.Forms.Resource.Layout.week = global::XLabs.Sample.Droid.Resource.Layout.week;
			global::XLabs.Forms.Resource.String.ApplicationName = global::XLabs.Sample.Droid.Resource.String.ApplicationName;
			global::XLabs.Forms.Resource.String.Hello = global::XLabs.Sample.Droid.Resource.String.Hello;
			global::XLabs.Forms.Resource.String.day_name_format = global::XLabs.Sample.Droid.Resource.String.day_name_format;
			global::XLabs.Forms.Resource.String.full_date_format = global::XLabs.Sample.Droid.Resource.String.full_date_format;
			global::XLabs.Forms.Resource.String.invalid_date = global::XLabs.Sample.Droid.Resource.String.invalid_date;
			global::XLabs.Forms.Resource.String.library_name = global::XLabs.Sample.Droid.Resource.String.library_name;
			global::XLabs.Forms.Resource.String.month_name_format = global::XLabs.Sample.Droid.Resource.String.month_name_format;
			global::XLabs.Forms.Resource.Style.CalendarCell = global::XLabs.Sample.Droid.Resource.Style.CalendarCell;
			global::XLabs.Forms.Resource.Style.CalendarCell_CalendarDate = global::XLabs.Sample.Droid.Resource.Style.CalendarCell_CalendarDate;
			global::XLabs.Forms.Resource.Style.CalendarCell_DayHeader = global::XLabs.Sample.Droid.Resource.Style.CalendarCell_DayHeader;
			global::XLabs.Forms.Resource.Style.CalendarTitle = global::XLabs.Sample.Droid.Resource.Style.CalendarTitle;
			global::XLabs.Platform.Resource.String.ApplicationName = global::XLabs.Sample.Droid.Resource.String.ApplicationName;
			global::XLabs.Platform.Resource.String.Hello = global::XLabs.Sample.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int calendar_active_month_bg = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int calendar_bg = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int calendar_divider = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int calendar_highlighted_day_bg = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int calendar_inactive_month_bg = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int calendar_selected_day_bg = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int calendar_selected_range_bg = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int calendar_text_active = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int calendar_text_inactive = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int calendar_text_selected = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int calendar_text_selector = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int calendar_text_unselectable = 2131099658;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070000
			public const int calendar_day_headers_paddingbottom = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int calendar_month_title_bottommargin = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int calendar_month_topmargin = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int calendar_text_medium = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int calendar_text_small = 2131165188;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ad16 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int alert = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int alert2 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ap_1024x1024_icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int appicon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int calendar_bg_selector = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int call = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int call2 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int carsacn = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int carsafe = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int carscan2 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int carscan3 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int chart = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int clock = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int clock2 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int dandrive = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int dandrive2 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int fast = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int gasolin = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int gasolin2 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int Icon = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int icon_152x152 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int icon_facebook = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int icon_google = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int icon_microsoft = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int icon_twitter = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int imgNotAvailable = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int invalid = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int locate = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int locate2 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int monoandroidsplash = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int nocar = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int nouser = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int panic = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int people = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int pie27_32 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int pie30_32 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int safe = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int safe2 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int search = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int services1_32 = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int settings20_32 = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int tobefinish = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int trace = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int trace2 = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int valid = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int vehicle = 2130837550;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090004
			public const int calendar_grid = 2131296260;
			
			// aapt resource value: 0x7f090001
			public const int calendar_view = 2131296257;
			
			// aapt resource value: 0x7f090003
			public const int left_arrow = 2131296259;
			
			// aapt resource value: 0x7f090002
			public const int right_arrow = 2131296258;
			
			// aapt resource value: 0x7f090000
			public const int title = 2131296256;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int calendar_pager_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int calendar_picker = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int dialog = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int month = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int week = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int day_name_format = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int full_date_format = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int invalid_date = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int library_name = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int month_name_format = 2131034117;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080001
			public const int CalendarCell = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int CalendarCell_CalendarDate = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int CalendarCell_DayHeader = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int CalendarTitle = 2131230720;
			
			// aapt resource value: 0x7f080004
			public const int Mono_Android_Theme_Splash = 2131230724;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int nfc = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
